server {
    listen 80;

    # ==============================================================================================
    # ROOT DIRECTORY
    root /var/www/public;
    index index.php index.html;

    # ==============================================================================================
    # ROUTING
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # ==============================================================================================
    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    }

    # Blokir akses ke file .htaccess
    location ~ /\.ht {
        deny all;
    }

    client_max_body_size 50M;
}